export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LIST_FILTERED_REQUEST = 'PRODUCT_LIST_FILTERED_REQUEST';
export const PRODUCT_LIST_FILTERED_SUCCESS = 'PRODUCT_LIST_FILTERED_SUCCESS';
export const PRODUCT_LIST_FILTERED_FAIL = 'PRODUCT_LIST_FILTERED_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_SUBCATEGORY_LIST_REQUEST = 'PRODUCT_SUBCATEGORY_LIST_REQUEST';
export const PRODUCT_SUBCATEGORY_LIST_SUCCESS = 'PRODUCT_SUBCATEGORY_LIST_SUCCESS';
export const PRODUCT_SUBCATEGORY_LIST_FAIL = 'PRODUCT_SUBCATEGORY_LIST_FAIL';
